# Generated by Django 6.0.1 on 2026-01-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0004_auto_20200527_1733"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YanGooAnalytics",
        ),
        migrations.AlterField(
            model_name="indexinsubinf",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
